#!/bin/bash

# OPTIONS
SECRET=""

# STUFF
usage() { 
echo "Usage:" 
echo "    -m \"<message>\"   - The notification text." 
echo "    -t \"<title>\"     - A custom message title. [optional] "
echo "    -l <level>       - The importance level from 1(low) to 5(high). [optional]" 
echo "    -u <link>        - An optional link. [optional]" 
echo "    -s <secret>      - The service secret token. [optional]" 
echo 
echo "Secret must be set on options of $0 or with -s <secret>"
exit 0; }

while getopts ":s:u:l:t:m:h:" o; do
	case "${o}" in
	    s)
	        s=${OPTARG}
	        ;;
		u)
			u=${OPTARG}
			;;
		l)
			l=${OPTARG}
			;;
		t)
			t=${OPTARG}
			;;
		m)
			m=${OPTARG}
			;;
	    h|-help)
	        usage
	        ;;
        \? )
            echo "Invalid Option: -$OPTARG" 1>&2
            exit 1
            ;;	        
		*)
			usage
			;;
	esac
done
shift $((OPTIND-1))

if [ -z "${m}" ]; then
  usage
	return 1
fi

if [ -z "${s}" ] && [ -z $SECRET ]; then
   echo "You may specify your secret with -s <SECRET> or define it on $0 options"
   exit 2
fi

if [ -n "${l}" ]; then    
	  level="${l}"
else
	  level="3"
fi

if [ -n "${t}" ]; then    
	  title="${t}"
else
	  title=""
fi

if [ -n "${s}" ]; then
      secret="${s}"
else
      secret="${SECRET}"
fi 

      
curl --data "secret=${secret}" --data-urlencode "message=${m}" --data "level=${level}" --data-urlencode "title=${title}" --data "link=${u}" https://api.pushjet.io/message > /dev/null 2>&1
