#!/bin/bash

# pushjet-cli simple cli interface to the PushJet API
# Website - https://github.com/Generator/pushjet-cli
# Author: Generator - https://github.com/Generator


usage() { 
echo "Usage: 
    -m \"<message>\"   - The notification text.
    -t \"<title>\"     - A custom message title. [optional] 
    -l <level>       - The importance level from 1(low) to 5(high). [default 3]
    -u <link>        - An optional link. 
    -s <secret>      - The service secret token.
    -S               - Custom server URL.
    -C               - Custom configuration.    
    -h               - Show help."
exit 0; }

if [ ! "$(which curl)" ]; then
	"pushjet-cli requires curl to run. Please install curl."
	exit 2
fi

while getopts ":s:u:l:t:m:h:S:C:" o; do
	case "${o}" in
	    s)
	        s=${OPTARG}
	        ;;
		S)
			S=${OPTARG}
			;;
		C)
			C=${OPTARG}
			;;				
		u)
			u=${OPTARG}
			;;		
		l)
			l=${OPTARG}
			;;
		t)
			t=${OPTARG}
			;;
		m)
			m=${OPTARG}
			;;
	    h)
	        usage
	        ;;
        \? )
            echo "Invalid Option: -$OPTARG" 1>&2
            exit 1
            ;;	        
		*)
			usage
			;;
	esac
done
shift $((OPTIND-1))

if [ -z "${m}" ]; then
  usage
	return 1
fi

# source configuration file

if [ -n "${C}" ]; then    
	  pushjetcfg="${C}"
	  . $pushjetcfg
elif [ -r $HOME/.config/pushjet-cli ]; then
    pushjetcfg=$HOME/.config/pushjet-cli
    . $pushjetcfg	  
elif [ -r /etc/pushjet-cli ]; then
      pushjetcfg=/etc/pushjet-cli
      . $pushjetcfg
fi


if [ -z "${s}" ] && [ -z $SECRET ]; then
   echo "You may enter your secret on one configuration file: 
       /etc/pushjet-cli 
       ~/.config/pushjet-cli
       
  Or use -s <SECRET>"
   exit 2
fi

if [ -n "${l}" ]; then    
	  level="${l}"
else
	  level="3"
fi

if [ -n "${t}" ]; then    
	  title="${t}"
else
	  title=""
fi

if [ -n "${s}" ]; then
      secret="${s}"
else
      secret="${SECRET}"
fi 

if [ -n "${S}" ]; then
      SERVERURL="${S}"
elif [ -z $SERVERURL ]; then
      SERVERURL="https://api.pushjet.io"
fi 

      
curl --data "secret=${secret}" --data-urlencode "message=${m}" --data "level=${level}" --data-urlencode "title=${title}" --data "link=${u}" ${SERVERURL}/message > /dev/null 2>&1
